workspace:
  base: /code
  path: src/github.com/LarryZhangy/optaplanner

pipeline:
  build:
    image: circleci/openjdk:8-jdk-browsers
    commands:
      - mvn clean package -DskipTests -Dcheckstyle.skip=true